package studentportal.datamodel;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Student")
@XmlRootElement
public class Student {
	private String Id;
	private String firstName;
	private String lastName;
	private String studentId;
	private String programID;
	private List<String> coursesEnrolled;

	public Student() {

	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	public Student(String firstName, String lastName, String studentID) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.studentId = studentID;

	}

	@DynamoDBIndexHashKey(attributeName = "studentId", globalSecondaryIndexName = "studentId-index")
	public String getStudentID() {
		return studentId;
	}

	public void setStudentID(String studentID) {
		this.studentId = studentID;
	}

	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Override
	public String toString() {
		return "StudentId=" + getStudentID() + ", firstName=" + getFirstName() + ", Program = " + getprogramID();

	}

	@DynamoDBAttribute(attributeName = "programId")
	public String getprogramID() {
		return programID;
	}

	public void setprogramID(String programID) {
		this.programID = programID;
	}

	@DynamoDBAttribute(attributeName = "coursesEnrolled")
	public List<String> getCoursesEnrolled() {
		return coursesEnrolled;
	}

	public void setCoursesEnrolled(List<String> coursesEnrolled) {
		this.coursesEnrolled = coursesEnrolled;
	}
}
